# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/5b004370-c2c3-4305-9930-6589f58b4a85/transcription
Content-Type: application/json

{
    "prompt": "música"
}


###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "5b004370-c2c3-4305-9930-6589f58b4a85",
    "temperature": 0.5,
    "template": "Gera um resumo sucinto da transcrição do video informado a seguir: ''' {transcription} ''' "

}